apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce，表示这个 Volume 的挂载方式是可读写，并且只能被挂载在一个节点上而非 被多个节点共享。
  resources:
    requests:
      storage: 1Gi




































# Persistent Volume Claim(PVC)和 Persistent Volume(PV)的 API 对象







